name: ampify
description: "Your ultimate companion to enhance, organize, and personalize your Music experience"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.1.0+1

# if changed/modified icon, run this command ater changing the path to icon in yaml file
# dart run flutter_native_splash:create --path=native_splash.yaml

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. 
dependencies:
  flutter:
    sdk: flutter

  # firebase 
  firebase_core: ^3.4.0
  firebase_messaging: ^15.0.1
  firebase_crashlytics: ^4.1.3
  # firebase_analytics: ^11.3.3
  # state n' route management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  rxdart: ^0.28.0
  get_it: ^8.0.2
  get_storage: ^2.1.1
  go_router: ^16.0.0
  # audio player
  just_audio: ^0.10.4
  audio_service: ^0.18.17
  audio_session: ^0.2.2
  youtube_explode_dart: ^2.3.6
  dart_ytmusic_api: ^1.0.8
  palette_generator: ^0.3.3+5
  # network & redirects
  dio: ^5.7.0
  app_links: ^6.3.2
  flutter_web_auth_2: ^4.1.0
  cached_network_image: ^3.4.1

  responsive_framework: ^0.1.4
  flutter_native_splash: ^2.4.3
  fluttertoast: ^8.2.8
  flutter_dotenv: ^5.2.1
  html_unescape: ^2.0.0
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/icons/
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
